# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
canonical: https://gematik.de/fhir/erezept-api-examples

status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1
FSHOnly: true

dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.5.2
  
  #kbv
  kbv.ita.erp: 1.2.0
  kbv.itv.evdga: 1.2.0
  kbv.ita.for: 1.2.0

  #gematik-epa
  de.gematik.epa.medication: 1.0.5-1
  de.gematik.terminology: 1.0.5
  
  # gematik
  de.gematik.erezept-workflow.r4: 1.5.0-rc3
  de.gematik.erezept.eu: 1.0.0-rc4
  de.gematik.erezept-patientenrechnung.r4: 1.1.0-rc2
  de.gematik.fhir.directory: 0.11.25
  de.gematik.ti: 1.1.0
  
  # abda
  de.abda.erezeptabgabedatenpkv: 1.4.0
  de.abda.erezeptabgabedaten: 1.5.0
  de.abda.erezeptabgabedatenbasis: 1.5.0
