# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
canonical: https://gematik.de/fhir/erezept-api-examples

status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1
FSHOnly: true

dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.5.0
  de.gematik.epa.medication: 1.1.1
  #kbv
  kbv.basis: 1.3.0
  kbv.ita.for: 1.1.x
  kbv.ita.erp: 1.2.0-alpha
  kbv.itv.evdga: 1.1.x
  # gematik
  de.gematik.erezept-workflow.r4: 1.5.0-beta10
  de.gematik.erezept-patientenrechnung.r4: 1.0.x
  de.gematik.fhir.directory: 0.11.12
  # abda
  de.abda.erezeptabgabedatenpkv: 1.3.0
  de.abda.erezeptabgabedaten: 1.4.x
  de.abda.erezeptabgabedatenbasis: 1.4.1
