# This is a basic workflow that is manually triggered

name: Build API examples

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      profileVersion:
        description: 'Profile version'
        default: '1.3'
        required: true
        type: string
      srcDirectory:
        description: 'Source directory for FSH files'
        default: '.\API-Examples\FSH-Files\orig_fsh_files'
        required: true
        type: string
      destDirectory:
        description: 'Directory for new FSH files'
        default: '.\API-Examples\FSH-Files\input'
        required: true
        type: string
      inputDirectory:
        description: 'Directory for the generated JSON files'
        default: '.\API-Examples\FSH-Files\fsh-generated\resources'
        required: true
        type: string
      outputDirectory:
        description: 'Directory for the converted files'
        default: '.\API-Examples\FSH-Files\output'
        required: true
        type: string
      templateDirectory:
        description: 'Which folder to use as template'
        default: '.\API-Examples\2024-11-01'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-examples"
  build_examples:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # defaults:
    #  run: 
    #    working-directory: ./API-Examples/FSH-Files
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    # Runs a single command using the runners shell
    - name: Execute main script
      run: ./API-Examples/FSH-Files/main.sh
