name: Validate Examples - HAPI - Copy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VALIDATOR_VERSION: 1.0.61
  PATH_TO_EXAMPLES: './temp_folder/'
  FHIR_VERSION: "4.0"
  INPUT_JAVA_VALIDATION_OPTIONS: "-tx http://tx.fhir.org -debug -allow-example-urls true"
  IG_DEPENDENCIES: "-ig de.basisprofil.r4#1.4.0 -ig hl7.fhir.r4.core#4.0.1 -ig kbv.ita.for#1.1.0 -ig kbv.ita.erp#1.1.x -ig de.gematik.erezept-workflow.r4"
#PATH_TO_EXAMPLES: 'API-Examples/FSH-Files/fsh-generated/resources/' 

jobs:
  CI_EXAMPLES_VALIDATION:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Identify and Copy Changed .json and .xml Files
      - name: Identify and Copy Changed .json and .xml Files
        run: |
          mkdir -p $PATH_TO_EXAMPLES # Create a temp folder
          # git fetch origin main:main
          git diff --name-only origin/main | grep -E '\.(json|xml)$' | xargs -I {} cp {} $PATH_TO_EXAMPLES/
          echo "Number of changed files to validate: " && ls -1 $PATH_TO_EXAMPLES | wc -l
      
      # Install Java runtime (only needed if you want to run the offical HL7 Java validator)
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
        
      # Install .NET runtime
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Firely.Terminal (GitHub Actions)
        uses: FirelyTeam/firely-terminal-pipeline@v0.6.12
        with:
          PATH_TO_CONFORMANCE_RESOURCES: API-Examples/FSH-Files/fsh-generated/resources/
          #FIRELY_TERMINAL_VERSION: 3.3.2
          PATH_TO_EXAMPLES: $PATH_TO_EXAMPLES
          #PATH_TO_QUALITY_CONTROL_RULES: qc/custom
          DOTNET_VALIDATION_ENABLED: true
          JAVA_VALIDATION_ENABLED: true
          #OUTPUT_FORMAT: RAW
          JAVA_VALIDATION_OPTIONS: -allow-example-urls true -output-style raw
          #JAVA_VALIDATOR_VERSION: 6.5.11
          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
          #SUSHI_ENABLED: true
          #SUSHI_VERSION: 3.11.0
          #SUSHI_OPTIONS: -s API-Examples/FSH-Files/
          EXPECTED_FAILS: VALIDATION_CONFORMANCE_DOTNET VALIDATION_CONFORMANCE_JAVA VALIDATION_EXAMPLES_JAVA
          ZTS_ENABLED: false
          JAVA_SNAPSHOT_ENABLED: true
  
      #- name: Check for Uncommitted Changes
      #  run: |
      #    git diff --exit-code 'API-Examples/FSH-Files/fsh-generated/resources'|| (echo "Es gibt Änderungen durch die Pipeline. Lokale Sushi Konfiguration prüfen!" && exit 1)              

      - name: Cleanup
        if: always()
        run: rm -rf temp_folder
